### ISSUE TITLE
[Bug] Manti-Toil death behavior

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-ToilHead#5]
Hey there,

When killed, the manti-toils corpses remain at the place of death, and begin spinning about their center.  The turret remains active, searching for targets.  When a target is observed, the turret works as if live (attempts to complete brief lock-on before firing).

**Comment by ghost** [comment]
Manticoils remaining in place and spinning around when they die is actually base game / vanilla behavior. They behave like that by design (or maybe lack-of, idk ask Zeekers). I don't think this is actually a bug.

Turrets still being active when the attached entity dies is also intended behavior I am pretty sure, as toilheads place a live turret on the head of the victims they manage to kill when doing contact damage. This is also mentioned in the config.

**Comment by JohnMetroid** [comment]
I wasn't trying to suggest the corpse itself was manti-toil-specific behavior, simply documented what occurs.  The persistent, rotating turret attached to the corpse definitely feels like it should be addressed as a bug.  The continued presence of a broken turret isn't something that can be meaningfully played around.


There also appears to be an issue with the manti-toil limit in the config.  I have it set to 3, but I regularly see 6+ manti-toils

**Comment by ZehsTeam** [comment]
@ajsglist This is intended death behavior.

I'll have to look into the Manti-Toil settings that are not working properly.
